FROM node:22.14

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
USER node
RUN pwd
RUN npm install

COPY --chown=node:node . .

RUN npm run build

EXPOSE 5000
ENTRYPOINT ["node", "dist/index.js"]