apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: web
spec:
  containers:
  - name: node-pod
    image: panupongdeve/node-pod:multi-stages-v2
    # image: docker-nodejs:multi-stages-v2
    ports:
    - containerPort: 5000
    env:
    - name: HOST
      value: '0.0.0.0'